spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca_prog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bibliouser
    password: biblio_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: programycl@gmail.com          # <-- tu correo de Gmail
    password: usyx xuhh npkd mrne      # <-- la de 16 caracteres
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

app:
  base-url: http://localhost:8080
  mail:
    from: "Biblioteca de programación <programycl@gmail.com>"   # <-- que coincida con el Gmail
